//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sample.Localization.SampleResources", typeof(SampleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Button_TestIt {
            get {
                return ResourceManager.GetString("Button_TestIt", resourceCulture);
            }
        }
        
        internal static string ErrorButton_Retry {
            get {
                return ResourceManager.GetString("ErrorButton_Retry", resourceCulture);
            }
        }
        
        internal static string ErrorType_Network {
            get {
                return ResourceManager.GetString("ErrorType_Network", resourceCulture);
            }
        }
        
        internal static string ErrorType_NoData {
            get {
                return ResourceManager.GetString("ErrorType_NoData", resourceCulture);
            }
        }
        
        internal static string ErrorType_None {
            get {
                return ResourceManager.GetString("ErrorType_None", resourceCulture);
            }
        }
        
        internal static string ErrorType_Server {
            get {
                return ResourceManager.GetString("ErrorType_Server", resourceCulture);
            }
        }
        
        internal static string ErrorType_Unknown {
            get {
                return ResourceManager.GetString("ErrorType_Unknown", resourceCulture);
            }
        }
        
        internal static string Error_Business {
            get {
                return ResourceManager.GetString("Error_Business", resourceCulture);
            }
        }
        
        internal static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        internal static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        internal static string DefaultLayout_Description_1 {
            get {
                return ResourceManager.GetString("DefaultLayout_Description_1", resourceCulture);
            }
        }
        
        internal static string DefaultLayout_Description_2 {
            get {
                return ResourceManager.GetString("DefaultLayout_Description_2", resourceCulture);
            }
        }
        
        internal static string DefaultLayout_Title {
            get {
                return ResourceManager.GetString("DefaultLayout_Title", resourceCulture);
            }
        }
        
        internal static string Title_TaskLoaderView {
            get {
                return ResourceManager.GetString("Title_TaskLoaderView", resourceCulture);
            }
        }
        
        internal static string ErrorEmulator_Title {
            get {
                return ResourceManager.GetString("ErrorEmulator_Title", resourceCulture);
            }
        }
        
        internal static string CustomLayout_Description_1 {
            get {
                return ResourceManager.GetString("CustomLayout_Description_1", resourceCulture);
            }
        }
        
        internal static string CustomLayout_Description_2 {
            get {
                return ResourceManager.GetString("CustomLayout_Description_2", resourceCulture);
            }
        }
        
        internal static string CustomLayout_Title {
            get {
                return ResourceManager.GetString("CustomLayout_Title", resourceCulture);
            }
        }
        
        internal static string Empty_Screen {
            get {
                return ResourceManager.GetString("Empty_Screen", resourceCulture);
            }
        }
        
        internal static string ErrorType_ErrorOnRefresh {
            get {
                return ResourceManager.GetString("ErrorType_ErrorOnRefresh", resourceCulture);
            }
        }
        
        internal static string Lottie_Description {
            get {
                return ResourceManager.GetString("Lottie_Description", resourceCulture);
            }
        }
        
        internal static string Lottie_Title {
            get {
                return ResourceManager.GetString("Lottie_Title", resourceCulture);
            }
        }
        
        internal static string NotStartedView_Description {
            get {
                return ResourceManager.GetString("NotStartedView_Description", resourceCulture);
            }
        }
        
        internal static string NotStartedView_Title {
            get {
                return ResourceManager.GetString("NotStartedView_Title", resourceCulture);
            }
        }
        
        internal static string SkeletonLoading_Description_1 {
            get {
                return ResourceManager.GetString("SkeletonLoading_Description_1", resourceCulture);
            }
        }
        
        internal static string SkeletonLoading_Description_2 {
            get {
                return ResourceManager.GetString("SkeletonLoading_Description_2", resourceCulture);
            }
        }
        
        internal static string SkeletonLoading_Title {
            get {
                return ResourceManager.GetString("SkeletonLoading_Title", resourceCulture);
            }
        }
    }
}
