// ------------------------------------------------------------------------------------------------
// This code was generated by TeaForResource
// Created by Software Wizard
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression

namespace ResourceGenerator.Resources
{
    public static class SampleResourcesKeys
    {
        public static string[] AllItems
        {
			get
			{
				return new []
				{
 		            "Button_TestIt",
 		            "ErrorButton_Retry",
 		            "ErrorType_Network",
 		            "ErrorType_NoData",
 		            "ErrorType_None",
 		            "ErrorType_Server",
 		            "ErrorType_Unknown",
 		            "Error_Business",
 		            "Error_Network",
 		            "Error_Unknown",
 		            "DefaultLayout_Description_1",
 		            "DefaultLayout_Description_2",
 		            "DefaultLayout_Title",
 		            "Title_TaskLoaderView",
 		            "ErrorEmulator_Title",
 		            "CustomLayout_Description_1",
 		            "CustomLayout_Description_2",
 		            "CustomLayout_Title",
 		            "Empty_Screen",
 		            "ErrorType_ErrorOnRefresh",
 		            "Lottie_Description",
 		            "Lottie_Title",
 		            "NotStartedView_Description",
 		            "NotStartedView_Title",
 		            "SkeletonLoading_Description_1",
 		            "SkeletonLoading_Description_2",
 		            "SkeletonLoading_Title",
 		            "Commands_Description_1",
 		            "Commands_Description_2",
 		            "Commands_Title",
                 };
            }
        }

		public static string Button_TestIt = "Button_TestIt";
		public static string ErrorButton_Retry = "ErrorButton_Retry";
		public static string ErrorType_Network = "ErrorType_Network";
		public static string ErrorType_NoData = "ErrorType_NoData";
		public static string ErrorType_None = "ErrorType_None";
		public static string ErrorType_Server = "ErrorType_Server";
		public static string ErrorType_Unknown = "ErrorType_Unknown";
		public static string Error_Business = "Error_Business";
		public static string Error_Network = "Error_Network";
		public static string Error_Unknown = "Error_Unknown";
		public static string DefaultLayout_Description_1 = "DefaultLayout_Description_1";
		public static string DefaultLayout_Description_2 = "DefaultLayout_Description_2";
		public static string DefaultLayout_Title = "DefaultLayout_Title";
		public static string Title_TaskLoaderView = "Title_TaskLoaderView";
		public static string ErrorEmulator_Title = "ErrorEmulator_Title";
		public static string CustomLayout_Description_1 = "CustomLayout_Description_1";
		public static string CustomLayout_Description_2 = "CustomLayout_Description_2";
		public static string CustomLayout_Title = "CustomLayout_Title";
		public static string Empty_Screen = "Empty_Screen";
		public static string ErrorType_ErrorOnRefresh = "ErrorType_ErrorOnRefresh";
		public static string Lottie_Description = "Lottie_Description";
		public static string Lottie_Title = "Lottie_Title";
		public static string NotStartedView_Description = "NotStartedView_Description";
		public static string NotStartedView_Title = "NotStartedView_Title";
		public static string SkeletonLoading_Description_1 = "SkeletonLoading_Description_1";
		public static string SkeletonLoading_Description_2 = "SkeletonLoading_Description_2";
		public static string SkeletonLoading_Title = "SkeletonLoading_Title";
		public static string Commands_Description_1 = "Commands_Description_1";
		public static string Commands_Description_2 = "Commands_Description_2";
		public static string Commands_Title = "Commands_Title";
    }


}
// </auto-generated>
