// ------------------------------------------------------------------------------------------------
// This code was generated by TeaForResource
// Created by Software Wizard
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression

namespace Sample.Localization
{
    public static class SampleResources
    {
		public static string Button_TestIt = $"TEST IT";
		public static string ErrorButton_Retry = $"RETRY";
		public static string ErrorType_Network = $"Network Error thrown";
		public static string ErrorType_NoData = $"No Data returned";
		public static string ErrorType_None = $"No Error";
		public static string ErrorType_Server = $"Server Exception thrown";
		public static string ErrorType_Unknown = $"Unknown Error thrown";
		public static string Error_Business = $"\"It's not me, it's the backend.\"";
		public static string Error_Network = $"Couldn't reach the Internet.";
		public static string Error_Unknown = $"\"An ill wind is blowing...\"";
		public static string DefaultLayout_Description_1 = $"`TaskLoaderView` provides defaults layout for all the views matching your task states (Loading/Error/Success/Notification).";
		public static string DefaultLayout_Description_2 = $"Those layouts are stylable, you can provide converters for error image and message.{Environment.NewLine}Set the loader color, the retry button text, the font family used....";
		public static string DefaultLayout_Title = $"Default  Views";
		public static string Title_TaskLoaderView = $"Sharpnado's TaskLoaderView";
		public static string ErrorEmulator_Title = $"Error Emulation";
		public static string CustomLayout_Description_1 = $"You can define your own views for each task state.";
		public static string CustomLayout_Description_2 = $"The `TaskLoaderView` uses an AbsoluteLayout, so you can even position your custom views very precisely.";
		public static string CustomLayout_Title = $"User Custom Views";
		public static string Empty_Screen = $"Nothing here folks.";
		public static string ErrorType_ErrorOnRefresh = $"Error On Refresh";
		public static string Lottie_Description = $"Use Lottie files to unlock next level UI.{Environment.NewLine}    ";
		public static string Lottie_Title = $"Lottie Animations";
		public static string NotStartedView_Description = $"Create a custom user NotStartedView to display a view before the Task is ran.{Environment.NewLine}You can for example use it to start your task on demand.{Environment.NewLine}    ";
		public static string NotStartedView_Title = $"Not Started View";
		public static string SkeletonLoading_Description_1 = $"Supports the excellent Xamarin.Forms.Skeleton loading package by Horus.";
		public static string SkeletonLoading_Description_2 = $"Find an easier implementation of the pattern with static dummy entities.";
		public static string SkeletonLoading_Title = $"Skeleton loading";
		public static string Commands_Description_1 = $"You can bind a `TaskLoaderCommand` to any views to display UI feedback matching your command task state.";
		public static string Commands_Description_2 = $"It works super well with `CompositeTaskLoaderNotifier` and `Snackbar` :)";
		public static string Commands_Title = $"Commands/Snackbar";
    }


}
// </auto-generated>
